#!/usr/bin/env bash
# Install nginx on a remote server and configure it

# Update package lists
sudo apt update

# Install nginx
sudo apt install nginx -y

# Create index.html file
sudo tee /var/www/html/index.html >/dev/null <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Nginx</title>
</head>
<body>
    <h1>Holberton School</h1>
    <p>Welcome to nginx!</p>
</body>
</html>
EOF

# Restart nginx service
sudo systemctl restart nginx
